services:
  cassandra:
    container_name: cassandra
    image: cassandra:3.11
    restart: unless-stopped
    hostname: cassandra
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=1G
      - CASSANDRA_CLUSTER_NAME=thp
    volumes:
      - ./cassandra/data:/var/lib/cassandra/data
    networks:
      net:
          ipv4_address: 10.0.0.42

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.11.1
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - script.allowed_types= inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      net:
          ipv4_address: 10.0.0.43
  
  cortex:
    container_name: cortex
    image: thehiveproject/cortex:latest
    environment:
      - no_proxy=localhost,::1,172.0.0.1/8,127.0.0.1/8,10.0.0.0/16,10.0.0.40/29
      - 'JOB_DIRECTORY=/opt/cortex/jobs'
      - http_proxy=http://172.22.200.200:8080/
      - https_proxy=http://172.22.200.200:8080/

    ports:
      - '19001:9001'
    volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./cortex/log/:/var/log/cortex
      - /tmp:/tmp
      #- ./cortex/Cortex-Analyzers:/opt/cortex/analyzers
      #- .cortex/Cortex-Analyzers/analyzers.json:/opt/cortex/analyzers/analyzers.json
    privileged: true
    networks:
      net:
          ipv4_address: 10.0.0.44
      platform_connections:
          ipv4_address: 10.0.0.53 
      internet_gateway:
          ipv4_address: 10.0.0.76
  
  thehive:
    container_name: thehive
    image: 'thehiveproject/thehive4:latest'
    restart: unless-stopped
    ports:
      - '0.0.0.0:10900:9000'
    volumes:
      - ./thehive/application.conf:/etc/thehive/application.conf
      - ./thehive/data:/opt/thp/thehive/data
      - ./thehive/index:/opt/thp/thehive/index
    command:
      --cortex-port 9001
    networks:
      net:
          ipv4_address: 10.0.0.45
      platform_connections:
          ipv4_address: 10.0.0.54 
networks:
  net:
    driver: bridge
    internal: true
    ipam:
     config:
       - subnet: 10.0.0.40/29
  platform_connections:
      external: true
  internet_gateway:
      external: true
