services:
  cassandra:
    container_name: cassandra
    image: cassandra:3.11
    restart: unless-stopped
    hostname: cassandra
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=1G
      - CASSANDRA_CLUSTER_NAME=thp
    volumes:
      - ./cassandra/data:/var/lib/cassandra/data
    networks:
      net:
          ipv4_address: 10.0.0.42

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      # Comment-out the line below for a cluster of multiple nodes
      - discovery.type=single-node
      # Uncomment the line below below for a cluster of multiple nodes
      # - cluster.name=docker-cluster
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - cluster.name=hive
      - thread_pool.search.queue_size=5000
      - logger.org.elasticsearch.discovery="ERROR"
      - "ES_JAVA_OPTS=-Xms3G -Xmx3G"
    networks:
      net:
        ipv4_address: 10.0.0.43
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
  
  cortex:
    container_name: cortex
    image: thehiveproject/cortex:latest
    environment:
      - 'JOB_DIRECTORY=/opt/cortex/jobs'

    ports:
      - '19001:9001'
    volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./cortex/log/:/var/log/cortex
      - /tmp:/tmp
      #- ./cortex/Cortex-Analyzers:/opt/cortex/analyzers
      #- .cortex/Cortex-Analyzers/analyzers.json:/opt/cortex/analyzers/analyzers.json
    privileged: true
    networks:
      net:
          ipv4_address: 10.0.0.44
      platform_connections:
          ipv4_address: 10.0.0.53 
      internet_gateway:
          ipv4_address: 10.0.0.76
  
  thehive:
    container_name: thehive
    image: 'thehiveproject/thehive4:latest'
    restart: unless-stopped
    ports:
      - '0.0.0.0:10000:9000'
    volumes:
      - ./thehive/application.conf:/etc/thehive/application.conf
      - ./thehive/data:/opt/thp/thehive/data
      - ./thehive/index:/opt/thp/thehive/index
    command:
      --cortex-port 9001
    networks:
      net:
          ipv4_address: 10.0.0.45
      platform_connections:
          ipv4_address: 10.0.0.54 
volumes:
  esdata:
networks:
  net:
    driver: bridge
    internal: true
    ipam:
     config:
       - subnet: 10.0.0.40/29
  platform_connections:
      external: true
  internet_gateway:
      external: true
