services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.1
    hostname: wazuh-certs-generator
    volumes:
      - ./config/wazuh_indexer_ssl_certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml
    environment:
      - HTTP_PROXY="http://172.22.200.200:8080/"
      - HTTPS_PROXY="http://172.22.200.200:8080/"
      - NO_PROXY="localhost,::1,172.0.0.1/8,127.0.0.1/8,10.0.0.0/8"