version: '5'
services:
  redis:
    image: redis:7.2.4
    volumes:
      - redisdata:/data
    restart: no
    networks:
      opencti-net:
        ipv4_address: 10.0.0.4 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      # Comment-out the line below for a cluster of multiple nodes
      - discovery.type=single-node
      # Uncomment the line below below for a cluster of multiple nodes
      # - cluster.name=docker-cluster
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - thread_pool.search.queue_size=5000
      - logger.org.elasticsearch.discovery="ERROR"
      - "ES_JAVA_OPTS=-Xms${ELASTIC_MEMORY_SIZE} -Xmx${ELASTIC_MEMORY_SIZE}"
    networks:
      opencti-net:
        ipv4_address: 10.0.0.3
     
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}    
    command: server /data
    restart: always
    networks:
      opencti-net:
        ipv4_address: 10.0.0.5
  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_NODENAME=rabbitmq
    volumes:
      - amqpdata:/var/lib/rabbitmq
    restart: always
    networks:
      opencti-net:
        ipv4_address: 10.0.0.6 
  opencti:
    image: opencti/platform:6.0.0-fips
    environment:
      - http_proxy=http://172.22.200.200:8080/
      - https_proxy=http://172.22.200.200:8080/
      - HTTP_PROXY=http://172.22.200.200:8080/
      - HTTPS_PROXY=http://172.22.200.200:8080/
      - NO_PROXY=localhost,::1,172.0.0.1/8,127.0.0.1/8,10.0.0.1/8
      - no_proxy=localhost,::1,172.0.0.1/8,127.0.0.1/8,10.0.0.1/8
      - NODE_OPTIONS=--max-old-space-size=4000
      - APP__PORT=30020
      - APP__BASE_URL=${OPENCTI_BASE_URL}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://10.0.0.3:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
    ports:
      - "35000:30020"
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
    networks:
      opencti-net:
        ipv4_address: 10.0.0.2
      platform-connections:
        ipv4_address: 10.0.0.50
  worker:
    image: opencti/worker:6.0.0
    environment:
      - OPENCTI_URL=http://10.0.0.2:30020
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 3
    restart: always
    networks:
      - opencti-net
volumes:
  esdata:
  s3data:
  redisdata:
  amqpdata:
networks:
  opencti-net:
       external: true
  platform-connections:
      external: true
 
